from flask import Flask, request, jsonify
from flask_cors import CORS
from dotenv import load_dotenv
import os
from openai import OpenAI

load_dotenv()

app = Flask(__name__)
CORS(app)

GPT_API_KEY = os.environ.get("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")
if not GPT_API_KEY:
    raise RuntimeError("GPT_API_KEY environment variable is required.")

client = OpenAI(api_key=GPT_API_KEY)


@app.route("/analyze", methods=["POST"])
def analyze():
    """
    Accepts a golf swing upload from backend_flask along with an optional
    biomechanical summary generated by MediaPipe/OpenCV. GPT turns that summary
    into polished coaching feedback.
    """
    if "file" not in request.files:
        return jsonify({"error": "No file uploaded"}), 400

    if request.files["file"].filename == "":
        return jsonify({"error": "Empty filename"}), 400

    pose_summary = request.form.get("message") or request.form.get("summary")

    try:
        user_prompt = (
            "Provide an expert golf swing review using the pose summary below. "
            "Call out strengths, issues, and 2-3 concrete adjustments.\n\n"
            f"{pose_summary}"
            if pose_summary
            else "No pose summary was supplied, so share a generic encouragement."
        )

        completion = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are GolfSensei, a seasoned PGA instructor who writes "
                        "succinct, constructive coaching notes."
                    ),
                },
                {"role": "user", "content": user_prompt},
            ],
            max_tokens=500,
            temperature=0.6,
        )

        analysis = completion.choices[0].message.content.strip()
        return jsonify({"analysis": analysis, "status": "success"})

    except Exception as exc:
        return jsonify({"error": f"Analysis failed: {exc}"}), 500


@app.route("/chat", methods=["POST"])
def chat():
    """Chat endpoint for follow-up questions about the swing"""
    data = request.get_json()
    
    message = data.get("message", "")
    video_context = data.get("video_context", "")
    
    if not message:
        return jsonify({"error": "No message provided"}), 400

    try:
        # Create a chat completion with GPT
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are GolfSensei, a professional swing coach. "
                        "Answer in a supportive, specific tone."
                    ),
                },
                {
                    "role": "user",
                    "content": f"Video context:\n{video_context}\n\nGolfer question: {message}",
                },
            ],
            max_tokens=500,
            temperature=0.6,
        )

        reply = response.choices[0].message.content

        return jsonify({
            "reply": reply,
            "status": "success"
        })

    except Exception as e:
        return jsonify({"error": f"Chat failed: {str(e)}"}), 500


@app.route("/health", methods=["GET"])
def health():
    """Health check endpoint"""
    return jsonify({"status": "healthy", "service": "GPT Wrapper"}), 200


if __name__ == "__main__":
    app.run(debug=True, port=8000)
